spring.datasource.url=jdbc:postgresql://localhost:5432/library_db
spring.datasource.username=postgres
spring.datasource.password=Elevant6
spring.datasource.driver-class-name=org.postgresql.Driver
spring.web.resources.static-locations=file:uploads/,classpath:/static/
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.port=8081
itbook.api.url=https://api.itbook.store/1.0