spring.application.name=veebipood
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.url=jdbc:postgresql://dpg-d7ukj07avr4c73cpae80-a.oregon-postgres.render.com/veebipood_database_t8rw
spring.datasource.username=veebipood_user
spring.datasource.password=54qmwlQsmtQSV9EaWMuWeyW1R1gBN4qa

# veebipood_user
# 54qmwlQsmtQSV9EaWMuWeyW1R1gBN4qa
# postgresql://veebipood_user:54qmwlQsmtQSV9EaWMuWeyW1R1gBN4qa@dpg-d7ukj07avr4c73cpae80-a.oregon-postgres.render.com/veebipood_database_t8rw